### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by mabar** [renanhangai/gulp-rollup-stream#1]
I am not sure if write here or to rollup repository. But - is there a way, how to cache output of babel plugin? Waiting on compilation of es2015 costs a lot of time. Previously I had build like in a code under these words for caching unchanged files and only merging them every run.

```
gulp.task('js', function () {
  gulp.src("src/**/*.js")
          .pipe(cached("babel"))
          .pipe(babel({
            presets: ["es2015-native-modules"]
          }))
          .pipe(remember("babel"))
          .pipe(babel({
            plugins: [
              "transform-es2015-modules-commonjs"
            ]
          }))
          .pipe(gulp.dest("dest/"));
});
```

I have not found way how to do it with rollup. I want to use tree-shaking and es2015 imports, but output is still in commonJS when I replace second babel with gulp-rollup-stream and using babel as plugin is very slow

```
var cache;

gulp.task('js', function () {
  gulp.src("src/**/*.js")
          .pipe(cached("babel"))
          .pipe(babel({
            presets: ["es2015-rollup"]
          }))
          .pipe(remember("babel"))
          .pipe(rollup({
            cache: cache
          }))
          .pipe(gulp.dest("dest/"));
});
```

**Comment by rhangai** [comment]
I ended up doing this on v0.1.0 https://github.com/renanhangai/gulp-rollup-stream/commit/dc6d27a0cbd32ee7e5a1bde560f43b574fa48da3, and i think it is a nice solution to reuse the previous bundle object.

``` js
var cache;
function bundleCb( bundle ) { cache = bundle; }

gulp.task( 'js', function() {
    return gulp.src( 'src/entry.js' )
        .pipe( rollup({ cache: cache }, bundleCb ) )
        .pipe( gulp.dest( 'dest/' ) );
});
```

I don't think it can go better than this as this project is just a thin wrapper around rollup. But if you think of any better way, feel free to file a pull request :)

### Side Note

I don't know exactly what you want to do, but i think you are not creating the optimal stream.

Using this repo, it would be something like:

``` js
var cache;
function bundleCb( bundle ) { cache = bundle; }

gulp.task('js', function () {
   return gulp.src("src/entry.js") // Single entry point
          .pipe(rollup({
              cache: cache,
              plugins: [ /* babel stuff */ ],
          }, bundleCb))
          .pipe(gulp.dest("dest/"));
});
gulp.task('watch', function () {
   gulp.watch("src/**/*.js", ['js'] );
});
```

Check: https://github.com/rollup/rollup-plugin-babel
