### ISSUE TITLE
Gulp process : Sourcemaps broken

### ISSUE THREAD

**Issue by Muini** [renanhangai/gulp-rollup-stream#2]
Hello,

I was trying to integrate your plugin to a gulp process in a template, this is actually working fine except for the sourcemaps. It's working well without it, but when I add them, I got this error : 

> [TypeError: Cannot read property 'replace' of null]
> TypeError: Cannot read property 'replace' of null

Here is my task 'scripts' (ENV_DEV is just a boolean to true) :

```
var bundler;
gulp.task('scripts', function() {
    return gulp.src( conf.paths.scripts + '/app.js' )
    .pipe( gulpif(ENV_DEV, sourcemaps.init()) )
    .pipe(rollup({
        cache: bundler,
        format: "iife",
        sourceMap: true,
        plugins: [
            babel({
                exclude: 'node_modules/**',
            }),
            cjs({
                include: 'node_modules/**'
            }),
            globals(),
            resolve({
                jsnext: true,
                main: true
            })
        ]
    }, function(bundle){
        bundler = bundle;
    } )).on('error', handleError)
    .pipe( concat('app.min.js') )
    .pipe( gulpif(ENV_DEV, sourcemaps.write('.')) )
    .pipe( gulpif(!ENV_DEV, uglify().on('error', handleError)) )
    .pipe(gulp.dest(conf.paths.dist + '/scripts'));
});
```

Thanks for your work !

**Comment by rhangai** [comment]
Haven't really have the time to test it, but i think it is fixed. Feel free to comment.
Commit 1a0364e

**Comment by rhangai** [comment]
Oh, and i forgot, no need to `sourceMap: true` It is not used internally.
Just use the `sourmaps.init()`
