### ISSUE TITLE
extname is vue,but resolveJs change  extname 

### ISSUE THREAD

**Issue by Jetsly** [renanhangai/gulp-rollup-stream#3]
` ENOENT: no such file or directory, open 'index.vue.js'`
```
function resolveJs() {
	const file = path.resolve.apply( path, arguments );
	return ( path.extname( file ) !== '.js' ) ? file+'.js' : file;
}
```

**Comment by rhangai** [comment]
Fixed on a1e6e85, at least i think it is :). If there is any problems please feel free to comment

It is now on version 0.1.3.
